### PR TITLE
Add addElement and removeElement to update...

### PR DESCRIPTION
**Pull request by jpscaletti**
Add addElement and removeElement to update the internal list of responsive elements when you manually add/remove one to the DOM

### CODE REVIEW

**Comment by stevenvachon** [comment]
Is this project dead? Unless this PR has errors, this feature really needs to be merged.

**Comment by stevenvachon** [comment]
@kumailht ^

**Comment by kumailht** [comment]
I think there is a small error in the pull request if I'm not mistaken.

Adding an element to the 'el' variable is pointless because it will never be executed on.
You might be trying to update the 'el.responsive_elements' property which is being executed on.

I apologize for the super later response, probably forgot to check this pull request.
If someone can fix that, I'll merge it in.

**Comment by jpscaletti** [comment]
I'm sorry. It's fixed now.

**Comment by kumailht** [comment]
@jpscaletti Thank you for your contribution :-)

**Pull request merged**
